nameOverride: ""
fullnameOverride: ""
type: Namespace
name: simple-bank-namespace
labels:
  name: demo-a
ingress:
  enabled: true
  name: nginx
  controller: k8s.io/ingress-nginx
  redirect: true
  http: 
    name: simple-bank-ingress-http
    host: api.simplebank.test
    secretName: simple-bank-api-cert
  grpc:
    name: simple-bank-ingress-grpc
    protocol: GRPC
    host: gapi.simplebank.test
    secretName: simple-bank-gapi-cert
  hosts:
    - host: "api.simplebank.test"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: simple-bank-api-service
              port:
                number: 80
    - host: "gapi.simplebank.test"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: simple-bank-api-service
              port:
                number: 90
  tls: []
  # - hosts:
  #   - gapi.simplebank.test
  #   secretName: simple-bank-gapi-cert
  #   - api.simplebank.test
  #   secretName: simple-bank-api-cert
deployment:
  name: simple-bank-api-deployment
  imageName: bmigeri/simple-bank-api
  dockerTag: latest
  pullPolicy: Always
  replicas: 1
  ports:
  - containerPort: 8080
    name: http-server
  - containerPort: 9090
    name: grpc-server
app: simple-bank-api
dbSource: postgresql://root:secret@host.minikube.internal:5432/simple_bank?sslmode=disable
redisAddr: host.minikube.internal:6379
httpName: http-server
grpcName: grpc-server
memory: 128Mi
cpu: 500m
protocol: TCP
service:
  name: simple-bank-api-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    # port: 30005
    targetPort: http-server
    name: http-service
  - protocol: TCP
    port: 90
    # port: 30010
    targetPort: grcp-server
    name: grpc-service
httpPort: 80
grpcPort: 90
issuer:
  name: letsencrypt
  server: https://acme-v02.api.letsencrypt.org/directory
  secretName: letsencrypt-account-private-key
email: bmigeri@gmail.com
redis:
  auth:
    enabled: false


