apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- $issuerName := .Values.issuer.name -}}
  {{- $serviceName := .Values.service.name -}}
  {{- $grpcPort := .Values.grpcPort -}}
  {{- with .Values.ingress }}
  name: {{ .grpc.name }}
  annotations:
    # cert-manager.io/cluster-issuer: {{ $issuerName }}
    # nginx.ingress.kubernetes.io/ssl-redirect: {{ .redirect | quote}}
    nginx.ingress.kubernetes.io/backend-protocol: {{ .grpc.protocol | quote }}
spec:
  ingressClassName: {{ .name }}
  rules:
  {{- range hosts }}
  - host: {{ index .hosts 1 }}
  {{- end }}
  
  # tls:
  # - hosts:
  #   - {{ .grpc.host | quote }}
  #   secretName: {{ .grpc.secretName }}
{{- end }}