apiVersion: v1
kind: Service
metadata:
  {{- $app := .Values.app -}}
  {{- with .Values.service }}
  name: {{ .name }}
spec:
  selector:
    app: {{ $app }}
  ports:
  {{- range .ports }}
  - protocol: {{ .protocol }}
    port: {{ .port}}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
   {{- end }}
  type: {{ .type }}
  {{- end }}